// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAisg7duYhE_ZSpvnFP9Jc330oex8L5Ckc',
    appId: '1:733743510290:web:c84a037604b7bf86bf39cb',
    messagingSenderId: '733743510290',
    projectId: 'integrador-ana-julia',
    authDomain: 'integrador-ana-julia.firebaseapp.com',
    storageBucket: 'integrador-ana-julia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClZDMXBZIjSWwv3nBaapsNNNjM4xoj8Qg',
    appId: '1:733743510290:android:abe09cd65fdb8f35bf39cb',
    messagingSenderId: '733743510290',
    projectId: 'integrador-ana-julia',
    storageBucket: 'integrador-ana-julia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWv8V46o_AXW14o5a10Dq605o8MkR_GaA',
    appId: '1:733743510290:ios:28786967287a160cbf39cb',
    messagingSenderId: '733743510290',
    projectId: 'integrador-ana-julia',
    storageBucket: 'integrador-ana-julia.firebasestorage.app',
    iosBundleId: 'com.example.integrador',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWv8V46o_AXW14o5a10Dq605o8MkR_GaA',
    appId: '1:733743510290:ios:28786967287a160cbf39cb',
    messagingSenderId: '733743510290',
    projectId: 'integrador-ana-julia',
    storageBucket: 'integrador-ana-julia.firebasestorage.app',
    iosBundleId: 'com.example.integrador',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAisg7duYhE_ZSpvnFP9Jc330oex8L5Ckc',
    appId: '1:733743510290:web:ac8a2370a26eb815bf39cb',
    messagingSenderId: '733743510290',
    projectId: 'integrador-ana-julia',
    authDomain: 'integrador-ana-julia.firebaseapp.com',
    storageBucket: 'integrador-ana-julia.firebasestorage.app',
  );
}
